---
- name: Include system setup tasks
  ansible.builtin.include_tasks:
    file: setup.yml
    apply:
      tags:
        - setup
  tags:
    - always

- name: Setup backup
  ansible.builtin.include_tasks:
    file: backup.yml
    apply:
      tags:
        - backup
  tags:
    - always

- name: Include compreface deployment tasks
  ansible.builtin.include_tasks:
    file: compreface.yml
    apply:
      tags:
        - compreface
  tags:
    - always

- name: Include double-take deployment tasks
  ansible.builtin.include_tasks:
    file: double-take.yml
    apply:
      tags:
        - double-take
  tags:
    - always
