---
# TODO: Define default variables for double-take role
# Follow the pattern from uptime-kuma role:
#
# service_name: double-take
# service_port: "3000"
# service_data_dir: /var/lib/double-take
# service_config_dir: /etc/double-take
# service_user: double-take
# service_domain: double-take.local.iamrobertyoung.co.uk
# service_container_name: double-take
#
# backup_image_name: backup-toolkit
# backup_image_tag: local
# backup_from: /data
# backup_mosquitto_host: mosquitto.local.iamrobertyoung.co.uk
# backup_mosquitto_username: "home-assistant"
# backup_mosquitto_password: "password"
# backup_bucket_name: "home-server-backup.iamrobertyoung.co.uk"
#
# nginx_config_dir: /etc/nginx
# nginx_data_dir: /var/lib/nginx
# nginx_user: nginx
# nginx_service_name: nginx
#
# cert_dir: /etc/double-take/certs
